### ISSUE TITLE
Label Encoding vs One hot encoding

### ISSUE THREAD

**Issue by aguptaz** [sarangspadalkar/Black-Friday-Sales-Prediction#1]
Hi,
I was going through your project , you guys have done great job.
i have a question.
you have chosen two feature for one hot encoding(Occupation & City_Category) and rest cat variable for Label encoding ,any logic behind  it?

**Comment by sarangspadalkar** [comment]
Hello,
 Thank you for going through my repository. I hope it helped.

Coming back to the question, If you notice the occupation field has 20 unique values ranging from Occupation 1 to Occupation 20, the problem if we Label encode this field is that, it will label each unique value with a number say from 1 to 20. This may create a bias while predicting the target variable. Hence, chose to perform One-Hot Encoding on this column. You can choose Label to encode the  _City_Category_  column as it has very few unique categories and it would work well either way.
